name: blincar_app
description: "Aplicaci칩n m칩vil Blincar - Transporte seguro"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI b치sico
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Estado
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Network
  http: ^1.2.1
  dio: ^5.4.3+1
  get_it: ^7.6.9

  # Storage
  shared_preferences: ^2.2.2

  # 游댠 FIREBASE - AGREGAR ESTAS DEPENDENCIAS
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3

  # Maps y ubicaci칩n
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0

  # 游닟 VIDEO STREAMING - Para c치mara Hikvision
  flutter_vlc_player: ^7.4.0
  # Si flutter_vlc_player da problemas, alternativa:
  # video_player: ^2.9.1 (ya lo tienes)

  # Utilidades b치sicas
  intl: ^0.19.0
  dartz: ^0.10.1
  video_player: ^2.9.1
  flutter_svg: ^2.2.0
  flutter_native_splash: ^2.4.6
  centered_singlechildscrollview: ^0.2.0

  # 游댒 Notificaciones locales
  flutter_local_notifications: ^17.2.3

  # 游댕 Compartir links
  url_launcher: ^6.3.1
  share_plus: ^10.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/b-icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/b-icon.png"
    background_color: "#1a1a2e"
    theme_color: "#4f46e5"
  windows:
    generate: true
    image_path: "assets/icons/b-icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#1a1a1a"
  image: assets/images/b-splash.png
  branding: assets/images/b-logo-branding.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/w-splash.png
  branding_dark: assets/images/w-logo-branding.png
  android_12:
    image: assets/images/b-logo-branding.png
    image_dark: assets/images/w-logo-branding.png
    icon_background_color_dark: "#1a1a1a"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/video/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Black.ttf
