// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6aPZzAXrXrl0M6TtrTXtIUXXMMFzVlU',
    appId: '1:1069273290393:web:e89c6cdef1438d890a0a08',
    messagingSenderId: '1069273290393',
    projectId: 'blin-car1',
    authDomain: 'blin-car1.firebaseapp.com',
    databaseURL: 'https://blin-car1-default-rtdb.firebaseio.com',
    storageBucket: 'blin-car1.firebasestorage.app',
    measurementId: 'G-5J9NQE4N2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIf8-4M0nSIJfHfEiCaerMUiW4H3uaSzQ',
    appId: '1:1069273290393:android:ce7ba83506f77d2f0a0a08',
    messagingSenderId: '1069273290393',
    projectId: 'blin-car1',
    databaseURL: 'https://blin-car1-default-rtdb.firebaseio.com',
    storageBucket: 'blin-car1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0KnatAEw8aQcS_j6MacuTDDoV4swRu2s',
    appId: '1:1069273290393:ios:18f48afcc6ca78e90a0a08',
    messagingSenderId: '1069273290393',
    projectId: 'blin-car1',
    databaseURL: 'https://blin-car1-default-rtdb.firebaseio.com',
    storageBucket: 'blin-car1.firebasestorage.app',
    iosBundleId: 'com.example.blincarAppNew',
  );

}